// <auto-generated />
namespace Catalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RevertLastCommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevertLastCommit));
        
        string IMigrationMetadata.Id
        {
            get { return "201510240159308_RevertLastCommit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
